### ISSUE TITLE
KB: API migration recommendations

### ISSUE THREAD

**Issue by davidediruscio** [eclipse-researchlabs/scava#24]

**Comment by davidediruscio** [comment]
@md2manoppello : can I ask what this issue is about ?

**Comment by davidediruscio** [comment]
@mhow2 It provides recommendations about updating libraries on a project under development.
This functionality is under development.

**Comment by jdirocco** [comment]
The recommender is completely implemented  on KB side, and the KB provides many rest interfaces to support the API Migration:
* First of all, the /api/recommendation/version/ resource shows the user the known newer versions of her libraries.
* At this point, the project that the user is currently working on going to be built to a JAR, so it will be able to represent her project. (which is currently the client for the updated third party library). 
* Then, this JAR is going to be uploaded to the `/api/api-migration/M3Model` API, and the M3 model is going to be saved on her computer.
* After that, we will be able to initiate a request to the `/api/api-migration/detection/{coordV1}/{coordV2} ` API, with the maven coordinates of the target (coordV1) and the currently used (coordV2) versions of the library and the formerly saved M3 model of the project.
* At this point, `/api/api-migration/similar_migration_location/{coordV1}/{coordV2}` provides the rascal location of libraries that already migrated from coordV1 to coordV2 and the `/api/api-migration/similar_migration_snippet/{coordV1}/{coordV2}` returns the code snippets.
