### ISSUE TITLE
Some inconsistencies in the Search

### ISSUE THREAD

**Issue by davidediruscio** [eclipse-researchlabs/scava#61]
Hi,

When I launch the Project Search looking for 'json" I get a list of Projects talking about JSON. Great.
Then when I launch a second search looking for 'json parser', I get one single answer, fair enough, BUT this project is not present in the previous list.

Is it expected ?
Thanks a lot

**Comment by davidediruscio** [comment]
I know that I'm repeating myself but the plug-in "only" display the results got from the server.

**Comment by davidediruscio** [comment]
New DB dump will fix it.

**Comment by davidediruscio** [comment]
Dear @geryxyz
No worries, I got the point. Nevertheless, I don't know if any issue that I could find on KB could impact or not your UI. It is for this reason that I add you to the bug

**Comment by davidediruscio** [comment]
Dear @md2manoppello, could we keep it open until I very that the new version fixes the mentioned issue?
Thx

**Comment by davidediruscio** [comment]
@phkrief can we close this?

**Comment by davidediruscio** [comment]
Fixed! Thx

**Comment by davidediruscio** [comment]
Actually, the error is still there on the ow2 server (http://scava-dev.ow2.org). @md2manoppello is it expected for OW2?
Thanks

**Comment by jdirocco** [comment]
It is solved and the OW2 instance works as expected.
